version: '3.9'

services:
 health:
   build:
     context: .
   ports:
     - "8000:8000"
   volumes:
     - ./health:/health
   command: >
      sh -c "export FLASK_APP=app.py && \
      export FLASK_ENV=development && flask run"
